 let b = 2

try {

  let a = 2 + b
  console.log(a)
  console.log('successfully')

} catch(e) {

  console.log(e)
  console.log('Not Succesfully!!!')
  //throw new Error(e)

}

console.log('teste')